### ISSUE TITLE
on Crystal Report Converting First Page is ok But after the second seems wrong location

### ISSUE THREAD

**Issue by ercanacar** [stimulsoft/Importing.Tools#2]
[Hello,] I have second problem on converting from Crystal Report.
First Page elements locations is ok. But after the second page elements goes over the end of the first page.
So can you help me find reason of this wrong location calculation?
Where I must look or may I change some size calculations ?

I have added, page1 ok, but page2 elements moving over bottom of page 1, please look it.
Thank you.
![page1 ok](https://user-images.githubusercontent.com/16348688/51980555-0bea2000-2499-11e9-839a-0825210912ed.PNG)
![page2 wrong](https://user-images.githubusercontent.com/16348688/51980556-0bea2000-2499-11e9-9ecc-0767a5d35c00.PNG)

**Comment by VladimirBLR** [comment]
Hello,

In this case, a more detailed analysis of the report is required. Please send it to support@stimulsoft.com we will try to resolve this issue.

**Comment by ercanacar** [comment]
Hi, I have sent it yesterday.
Today I have found this bug doesn't exist on the JS designer.
All Winform, Wpf, Wpf2 designer has this bug, Elements doesnt located true position.
But in the JS designer interesting but it seems ok.
I'm trying to find more accurate converting options from Crystal Reports and customizing Import tool.
Especially calculating object size-location-position needs more accurate calculation formula but Really i don't know how we can fix it.
Thank you.
